language: python
os:
  - linux

python:
 - "2.7"

before_install:
  - sudo apt-add-repository -y ppa:travis-ci/phantomJS
  - sudo apt-get -y update
  - sudo apt-get -y install phantomJS

install: "pip install -r requirements.txt"
